version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: 4444

  robot-tests:
    build: .
    depends_on:
      - selenium-hub
      - chrome
    environment:
      BROWSER: chrome
    volumes:
      - .:/app
