*** Variables ***
# User credentials
${USERNAME}                         standard_user
${LOCKED_USERNAME}                  locked_out_user
${PROBLEM_USERNAME}                 problem_user
${PERFORMANCE_GLITCH_USERNAME}      performance_glitch_user
${INVALID_USERNAME}                 wrong_user

${PASSWORD}                         secret_sauce
${INVALID_PASSWORD1}                secrets_sauce
${INVALID_PASSWORD2}                wsecret_sauce
${INVALID_PASSWORD3}                secret_sauced
