name: Robot Framework Tests

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Build Docker image
      #   run: docker build -t robot-tests .

      - name: Start Selenium Grid and Run Tests
        run: |
          docker-compose up --abort-on-container-exit
      
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          browser: 'chrome'
          robot_threads: ${{ github.event.inputs.threads }}
          pabot_options: '--testlevelsplit'
          robot_tests_dir: tests
          robot_reports_dir: logs

      - name: Start Selenium Grid and Run Tests
        run: |
          docker-compose down

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: output/
