name: Testrun 2 Threads

on: [workflow_dispatch]
  inputs:
    threads:
      type: number
      required: true

jobs:
  run-robot-framework-tests:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Robot Framework
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        browser: 'chrome'
        robot_threads: 2
        robot_tests_dir: tests
        robot_reports_dir: logs