name: Build Release for Dev1

on: [workflow_dispatch]

jobs:
  run-robot-framework-tests:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Robot Framework
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        browser: 'chrome'
        robot_threads: 2
